version: '3.9'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - mysql
    ports:
      - "8000:80"

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: challenge
      MYSQL_USER: dba
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root